# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET build&[test]

on:
  workflow_call:
    inputs:
      dotnet_version:
        required: true
        type: string
      run_tests:
        required: false
        default: true
        type: boolean

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{inputs.dotnet_version}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      if: inputs.run_tests
      run: dotnet test --no-build --verbosity normal
