name: 'Helm Deploy'
description: 'Deploy Helm chart with custom values'

inputs:
  values:
    description: 'YAML string of Helm values'
    required: true
  release:
    description: "Helm release name"
    required: true
    type: string
  chart:
    description: "Helm chart to be used"
    required: true
    type: string
  namespace:
    description: "K8s namespace to execute against"
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Write YAML to file
      run: |
        cat <<'EOF' > custom-values.yaml
        ${{ inputs.values }}
        EOF
      shell: bash
      
    - name: Show custom-values.yaml
      run: |
        echo "===== custom-values.yaml ====="
        cat custom-values.yaml
      shell: bash
      
    - name: build dependencies
      run: helm dependency up ${{ inputs.chart }} 
      shell: bash
      
    - name: Render CronJob with line numbers
      run: |
        helm template ./schedulers/dynamic-extreme-prices-morning-scheduler/devops/helm \
          -f custom-values.yaml \
          --show-only templates/cronjob.yaml \
          --debug > rendered-cronjob.yaml || true
          
        echo "====== rendered-cronjob.yaml ======"
        nl -ba rendered-cronjob.yaml | sed -n '1,200p'
      shell: bash
      
    - name: Render all Helm templates (debug)
      run: |
        echo "===== Rendered Helm templates ====="
        helm template ${{ inputs.chart }} \
          -f custom-values.yaml \
          --debug > rendered-all.yaml || true
    
        nl -ba rendered-all.yaml | sed -n '1,300p'
      shell: bash
      
    - name: Deploy Helm Chart
      run: >
        helm upgrade --install 
        ${{ inputs.release }}  
        ${{ inputs.chart }} 
        --namespace ${{ inputs.namespace }} 
        -f custom-values.yaml
      shell: bash
