name: Docker Build&[Push] 

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      context:
        required: true
        type: string
      push:
        required: false
        default: false
        type: boolean
      regestry:
        required: false
        default: ghcr.io/powerchainger
        type: string
      application:
        required: true
        type: string
      push_as_latest:
        required: false
        default: false
        type: boolean
    outputs:
      image_tags:
        description: "The tags of probably published image"
        value: ${{jobs.push_to_registry.outputs.meta_tags}}

jobs:
  push_to_registry:
    name: Docker Build&[Push] 
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    outputs:
      meta_tags: ${{steps.meta.outputs.tags}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ inputs.regestry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Get docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{inputs.regestry}}/${{inputs.application}}
          tags: |
             type=raw,value={{branch}}-${{github.run_id}}-{{sha}},suffix=-${{github.run_number}}-${{github.run_attempt}}
             type=raw,value=latest,enable=${{inputs.push_as_latest}}
             
      - name: Print meta lables
        run: echo "${{ steps.meta.outputs.labels }}"
      - name: Print meta tags.
        run: echo "${{ steps.meta.outputs.tags }}"
      - name: Print meta version.
        run: echo "${{ steps.meta.outputs.version }}"
        
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ${{inputs.context}}
          file: ${{inputs.file}}
          push: ${{inputs.push}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
